# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Jae's Blog"
name: "Jae Hong Kim"
email: "jaehongkim86@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  My personal website and blog!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jaehongkim.xyz" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username:
github_username: "jkim-"

author:
  name: "Jae Hong Kim"
  #avatar: "path/to/img"
  bio: "PhD Candidate at Caltech"
  location: "Pasadena, CA"
  email: "jaehongkim86@gmail.com"
  linkedin: "jae-hong-kim"
  github: "jkim-"

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air"
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap

# Pagination
pagination:
  enabled: true
  debug: false
  per_page: 10
  permalink: "/page/:num/"
  title: ":title - Page :num of :max"
  limit: 0
  sort_field: "date"
  sort_reverse: true

# Search
search: true

# Reading files
keep_files:
  - .git
include:
  - _pages
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

defaults:
  # Posts settings
  - scope:
      path: _posts
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: false
  # Pages settings
  - scope:
      path: _pages
      type: pages
    values:
      layout: single

# Comments via staticman
repository: "jkim-/jaeblog"
comments:
  provider: "staticman_v2"
staticman:
  branch: "master"

# Analytics
analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-123362643-1"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
